name: music_player
description: A simple music player app
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.4.1
  sqflite_common_ffi: ^2.3.4+4
  path_provider: ^2.1.5
  provider: ^6.1.2
  just_audio: ^0.9.42
  audio_session: ^0.1.21
  share_plus: ^10.1.3
  url_launcher: ^6.3.1
  permission_handler: ^11.3.1
  audio_service: ^0.18.15


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  # permission_handler: ^10.2.0
  path: ^1.8.3

flutter:
  uses-material-design: true
  
  assets:
    - assets/icons/
